source 'http://rubygems.org'

gem 'rspec'
gem 'terminal-notifier-guard'
gem 'awesome_print'
gem 'rb-readline'
gem 'rubocop'
gem 'aruba'
gem 'cucumber'
gem 'faker'
gem 'simplecov'
gem 'simplecov-rcov'
